/**
 * RubyToolchain - resolves HOW to run a Ruby tool (rubocop, rails, rspec, ...) for a project.
 *
 * Priority: the project's own `bin/<tool>` binstub, else `bundle exec <tool>` when a Gemfile
 * exists, else the bare tool — each optionally wrapped in the project's version manager
 * (mise / asdf / rbenv / rvm) so the *project's* Ruby is used even when the extension host
 * was launched from a GUI without shell init. Pure and fs/PATH-injected, so it is unit-testable.
 */

import * as path from 'path'

export type VersionManager = 'none' | 'mise' | 'asdf' | 'rbenv' | 'rvm' | 'chruby'
export type VersionManagerSetting = 'auto' | VersionManager

export interface ToolchainEnv {
  exists(p: string): boolean
  readFile(p: string): string | undefined
  /** True if `command` is runnable from PATH (or a known install location). */
  onPath(command: string): boolean
  platform: NodeJS.Platform
}

export interface ResolvedCommand {
  command: string
  args: string[]
}

/** Tools whose binstub (`bin/<tool>`) is conventionally generated by Rails/Bundler. */
const BINSTUB_TOOLS = new Set(['rails', 'rake', 'rspec', 'rubocop', 'brakeman', 'steep', 'rbs', 'sidekiq', 'puma'])

function readTextIfExists(env: ToolchainEnv, p: string): string | undefined {
  return env.exists(p) ? env.readFile(p) : undefined
}

/** Which Ruby managers does the project's config files point at, in preference order. */
function candidateManagers(root: string, env: ToolchainEnv): VersionManager[] {
  const toolVersions = readTextIfExists(env, path.join(root, '.tool-versions'))
  const declaresRubyInToolVersions = Boolean(toolVersions && /^\s*ruby\s+\S+/m.test(toolVersions))
  const miseToml = ['.mise.toml', 'mise.toml'].some(f => {
    const text = readTextIfExists(env, path.join(root, f))
    return Boolean(text && /^\s*ruby\s*=/m.test(text))
  })
  const dotRubyVersion = env.exists(path.join(root, '.ruby-version')) || env.exists(path.join(root, '.rbenv-version'))

  const order: VersionManager[] = []
  if (miseToml || declaresRubyInToolVersions) {order.push('mise', 'asdf')}
  if (dotRubyVersion) {order.push('mise', 'rbenv', 'asdf', 'rvm', 'chruby')}
  return [...new Set(order)]
}

export function detectVersionManager(root: string, env: ToolchainEnv, setting: VersionManagerSetting = 'auto'): VersionManager {
  if (setting === 'none') {return 'none'}
  if (setting !== 'auto') {return env.onPath(setting === 'chruby' ? 'chruby-exec' : setting) ? setting : 'none'}
  // Windows has no rbenv/asdf/mise/rvm wrappers; RubyInstaller puts ruby on PATH.
  if (env.platform === 'win32') {return 'none'}
  for (const manager of candidateManagers(root, env)) {
    if (env.onPath(manager === 'chruby' ? 'chruby-exec' : manager)) {return manager}
  }
  return 'none'
}

function wrapWithManager(manager: VersionManager, root: string, cmd: ResolvedCommand, env: ToolchainEnv): ResolvedCommand {
  const inner = [cmd.command, ...cmd.args]
  switch (manager) {
    case 'mise': return { command: 'mise', args: ['exec', '--', ...inner] }
    case 'asdf': return { command: 'asdf', args: ['exec', ...inner] }
    case 'rbenv': return { command: 'rbenv', args: ['exec', ...inner] }
    case 'rvm': return { command: 'rvm', args: ['in', root, 'do', ...inner] }
    case 'chruby': {
      const version = readTextIfExists(env, path.join(root, '.ruby-version'))?.trim().replace(/^ruby-/, '')
      return version ? { command: 'chruby-exec', args: [version, '--', ...inner] } : cmd
    }
    case 'none': return cmd
  }
}

export interface ResolveOptions {
  manager: VersionManager
}

/**
 * Ordered candidates to try for `tool` — first is preferred, the rest are fallbacks used by
 * callers that previously did "bundle exec X, else bare X".
 */
export function rubyCommandCandidates(
  root: string,
  tool: string,
  args: readonly string[],
  env: ToolchainEnv,
  options: ResolveOptions,
): ResolvedCommand[] {
  const candidates: ResolvedCommand[] = []
  const stub = path.join(root, 'bin', tool)

  if (BINSTUB_TOOLS.has(tool) && env.exists(stub)) {
    // Binstubs are Ruby scripts; Windows can't exec them directly.
    candidates.push(env.platform === 'win32'
      ? { command: 'ruby', args: [stub, ...args] }
      : { command: stub, args: [...args] })
  }
  if (env.exists(path.join(root, 'Gemfile'))) {
    candidates.push({ command: 'bundle', args: ['exec', tool, ...args] })
  }
  candidates.push({ command: tool, args: [...args] })

  return candidates.map(c => wrapWithManager(options.manager, root, c, env))
}
