/**
 * RuntimeIntrospector - opt-in `rails runner` introspection.
 *
 * Static parsing (SchemaIndexer/RoutesIndexer) stays the default. This boots the Rails app
 * once and dumps what only the running framework knows: real associations, validations,
 * callbacks, routes and middleware. It EXECUTES APPLICATION CODE (initializers, eager load),
 * so callers must gate it behind explicit user opt-in / workspace trust.
 *
 * The Ruby side prints JSON between markers so unrelated boot output cannot corrupt parsing.
 */

export const BEGIN_MARKER = '__RAILSFORGE_JSON_BEGIN__'
export const END_MARKER = '__RAILSFORGE_JSON_END__'

export const INTROSPECTION_SCRIPT = `# frozen_string_literal: true
# Generated by RailsForge — read-only introspection, prints JSON and exits.
require 'json'

def rf_simple(value)
  case value
  when String, Numeric, true, false, nil then value
  when Symbol then value.to_s
  when Array then value.first(20).map { |v| rf_simple(v) }
  when Hash then value.first(20).to_h { |k, v| [k.to_s, rf_simple(v)] }
  else value.class.name
  end
end

def rf_options(options, keys)
  rf_simple((options || {}).select { |k, _| keys.include?(k) })
end

# Only callbacks defined in the application (not Rails' own autosave/normalization hooks).
def rf_app_callback?(model, filter)
  location = filter.respond_to?(:source_location) ? filter.source_location : (model.instance_method(filter).source_location rescue nil)
  !location.nil? && location.first.to_s.start_with?(Rails.root.to_s)
end

begin
  Rails.application.eager_load!
rescue StandardError => e
  warn "RailsForge: eager_load failed: #{e.class}: #{e.message}"
end

models = ActiveRecord::Base.descendants.reject(&:abstract_class?).sort_by { |m| m.name.to_s }.filter_map do |model|
  next if model.name.nil?

  begin
    {
      name: model.name,
      table: ((model.table_exists? ? model.table_name : nil) rescue nil),
      file: (Object.const_source_location(model.name)&.first),
      associations: model.reflect_on_all_associations.map do |a|
        {
          name: a.name.to_s,
          macro: a.macro.to_s,
          class_name: (a.polymorphic? ? nil : a.class_name),
          options: rf_options(a.options, %i[dependent through polymorphic inverse_of foreign_key counter_cache touch optional])
        }
      end,
      validations: model.validators.map do |v|
        { kind: v.kind.to_s, attributes: v.attributes.map(&:to_s), options: rf_options(v.options, %i[allow_nil allow_blank on if unless scope case_sensitive]) }
      end,
      callbacks: %i[validation save create update destroy commit rollback].flat_map do |kind|
        chain = model.respond_to?("_#{kind}_callbacks") ? model.send("_#{kind}_callbacks") : []
        chain.select { |c| rf_app_callback?(model, c.filter) }.map { |c| { event: kind.to_s, kind: c.kind.to_s, filter: (c.filter.is_a?(Symbol) ? c.filter.to_s : 'block') } }
      end
    }
  rescue StandardError => e
    { name: model.name, error: "#{e.class}: #{e.message}" }
  end
end

routes = Rails.application.routes.routes.map do |r|
  { verb: r.verb.to_s, path: r.path.spec.to_s, controller: r.defaults[:controller], action: r.defaults[:action], name: r.name }
end

snapshot = {
  rails: Rails.version,
  ruby: RUBY_VERSION,
  environment: Rails.env.to_s,
  models: models,
  routes: routes,
  middleware: Rails.application.middleware.map { |m| m.inspect }
}

puts "${BEGIN_MARKER}"
puts JSON.generate(snapshot)
puts "${END_MARKER}"
`

export interface RuntimeAssociation {
  name: string
  macro: string
  class_name: string | null
  options: Record<string, unknown>
}
export interface RuntimeValidation {
  kind: string
  attributes: string[]
  options: Record<string, unknown>
}
export interface RuntimeCallback {
  event: string
  kind: string
  filter: string
}
export interface RuntimeModel {
  name: string
  table: string | null
  file: string | null
  associations: RuntimeAssociation[]
  validations: RuntimeValidation[]
  callbacks: RuntimeCallback[]
  error?: string
}
export interface RuntimeRoute {
  verb: string
  path: string
  controller: string | null
  action: string | null
  name: string | null
}
export interface RuntimeSnapshot {
  rails: string
  ruby: string
  environment: string
  models: RuntimeModel[]
  routes: RuntimeRoute[]
  middleware: string[]
  /** ISO timestamp the snapshot was taken (added by the extension). */
  capturedAt?: string
}

const asArray = <T>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : [])
const asString = (v: unknown): string => (typeof v === 'string' ? v : '')
const asNullableString = (v: unknown): string | null => (typeof v === 'string' ? v : null)

/** Extracts and validates the JSON between the markers; undefined if absent or malformed. */
export function parseIntrospectionOutput(stdout: string): RuntimeSnapshot | undefined {
  const start = stdout.indexOf(BEGIN_MARKER)
  const end = stdout.indexOf(END_MARKER, start + BEGIN_MARKER.length)
  if (start === -1 || end === -1) {return undefined}

  let raw: Record<string, unknown>
  try {
    raw = JSON.parse(stdout.slice(start + BEGIN_MARKER.length, end).trim())
  } catch {
    return undefined
  }
  if (typeof raw !== 'object' || raw === null || !Array.isArray(raw.models)) {return undefined}

  const models = asArray<Record<string, unknown>>(raw.models).map((m): RuntimeModel => ({
    name: asString(m.name),
    table: asNullableString(m.table),
    file: asNullableString(m.file),
    associations: asArray<Record<string, unknown>>(m.associations).map(a => ({
      name: asString(a.name),
      macro: asString(a.macro),
      class_name: asNullableString(a.class_name),
      options: typeof a.options === 'object' && a.options !== null ? (a.options as Record<string, unknown>) : {},
    })),
    validations: asArray<Record<string, unknown>>(m.validations).map(v => ({
      kind: asString(v.kind),
      attributes: asArray<unknown>(v.attributes).map(asString),
      options: typeof v.options === 'object' && v.options !== null ? (v.options as Record<string, unknown>) : {},
    })),
    callbacks: asArray<Record<string, unknown>>(m.callbacks).map(c => ({ event: asString(c.event), kind: asString(c.kind), filter: asString(c.filter) })),
    ...(typeof m.error === 'string' ? { error: m.error } : {}),
  })).filter(m => m.name !== '')

  return {
    rails: asString(raw.rails),
    ruby: asString(raw.ruby),
    environment: asString(raw.environment),
    models,
    routes: asArray<Record<string, unknown>>(raw.routes).map(r => ({
      verb: asString(r.verb),
      path: asString(r.path),
      controller: asNullableString(r.controller),
      action: asNullableString(r.action),
      name: asNullableString(r.name),
    })),
    middleware: asArray<unknown>(raw.middleware).map(asString),
  }
}

/** Markdown report of a snapshot (models, associations, validations, callbacks, routes, middleware). */
export function formatSnapshotMarkdown(s: RuntimeSnapshot): string {
  const out: string[] = [
    '# Rails runtime introspection',
    '',
    `Rails ${s.rails} · Ruby ${s.ruby} · ${s.environment}${s.capturedAt ? ` · captured ${s.capturedAt}` : ''}`,
    '',
    `## Models (${s.models.length})`,
  ]
  for (const m of s.models) {
    out.push('', `### ${m.name}${m.table ? ` → \`${m.table}\`` : ''}`)
    if (m.error) {out.push(`_introspection error: ${m.error}_`); continue}
    for (const a of m.associations) {
      const opts = Object.entries(a.options).map(([k, v]) => `${k}: ${String(v)}`).join(', ')
      out.push(`- ${a.macro} \`${a.name}\`${a.class_name ? ` → ${a.class_name}` : ''}${opts ? ` (${opts})` : ''}`)
    }
    for (const v of m.validations) {out.push(`- validates ${v.attributes.join(', ')}: ${v.kind}`)}
    for (const c of m.callbacks) {out.push(`- ${c.kind}_${c.event}: ${c.filter}`)}
  }
  out.push('', `## Routes (${s.routes.length})`)
  for (const r of s.routes) {out.push(`- ${r.verb || 'ANY'} ${r.path} → ${r.controller ?? '(rack)'}#${r.action ?? ''}${r.name ? ` (${r.name})` : ''}`)}
  out.push('', `## Middleware (${s.middleware.length})`, ...s.middleware.map(m => `- ${m}`))
  return `${out.join('\n')}\n`
}
